package models

import (
	"encoding/json"

	"github.com/google/uuid"
)

// GeoJSONPolygon represents a GeoJSON Polygon object.
type GeoJSONPolygon struct {
	Type        string        `json:"type"` // Always "Polygon"
	Coordinates [][][]float64 `json:"coordinates"`
}

// LakeZone represents a spatial region of Lake Victoria.
type LakeZone struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	Name        string          `db:"name" json:"name"`
	Boundary    json.RawMessage `json:"boundary"` // Stored/Returned as GeoJSON Polygon
	RegionLabel string          `db:"region_label" json:"region_label"`
}

// LakeZoneDetail includes historical metrics, incident density, and active cages.
type LakeZoneDetail struct {
	Zone            LakeZone        `json:"zone"`
	CurrentMetrics  *ZoneMetrics    `json:"current_metrics"`
	ExpansionSignal *ExpansionSignal`json:"expansion_signal,omitempty"`
	IncidentCount   int             `json:"incident_count"`
	ActiveCageCount int             `json:"active_cage_count"`
}

// CopernicusPointTelemetry holds satellite-derived environmental telemetry for a specific lat/lng coordinate on Lake Victoria.
type CopernicusPointTelemetry struct {
	Latitude             float64   `json:"latitude"`
	Longitude            float64   `json:"longitude"`
	ZoneName             string    `json:"zone_name"`
	RegionLabel          string    `json:"region_label"`
	DissolvedOxygen      float64   `json:"dissolved_oxygen"`      // mg/L
	SurfaceTemperature   float64   `json:"surface_temperature"`   // °C
	PH                   float64   `json:"ph"`
	Turbidity            float64   `json:"turbidity"`             // NTU
	ChlorophyllA         float64   `json:"chlorophyll_a"`         // µg/L
	SecchiDepth          float64   `json:"secchi_depth"`          // meters
	AlgalBloomRisk       string    `json:"algal_bloom_risk"`      // 'low' | 'moderate' | 'high'
	RiskLevel            string    `json:"risk_level"`            // 'low' | 'moderate' | 'high'
	Trend                string    `json:"trend"`                 // 'improving' | 'stable' | 'deteriorating'
	SuitabilityScore     int       `json:"suitability_score"`     // 0-100 score for cage placement
	SatelliteSource      string    `json:"satellite_source"`      // e.g. "Sentinel-3 OLCI / SLSTR Instrument (CDSE)"
	ObservationTimestamp json.RawMessage `json:"observation_timestamp"`
	AIRecommendation     *AIRecommendation `json:"ai_recommendation,omitempty"`
}

// AIRecommendation represents actionable steps and recommendations generated by Groq AI.
type AIRecommendation struct {
	Summary              string   `json:"summary"`
	RiskScore            float64  `json:"risk_score"`
	RiskLevel            string   `json:"risk_level"`
	ActionableSteps      []string `json:"actionable_steps"`
	PreventativeMeasures []string `json:"preventative_measures"`
	AIModelUsed          string   `json:"ai_model_used"`
}
